"""
    ENERGY MODBUS PARAMS
"""

AMP = "A"
BYTE_ORDER = "bo"
DESC = "description"
ENABLED = "enabled"
ENERGY = "kWh"
FREQ = "Hz"
FUNCTION_CODE = "fc"
HI = "Hi"
L1 = "L1"
L2 = "L2"
L3 = "L3"
LO = "Lo"
NAME = "name"
NUMBER_OF_DECIMALS = "nod"
NUMBER_OF_REGISTERS = "nor"
POWER = "P"
REGISTER_ADDRESS = "ra"
SHORT = "short"
SIGNED = "s"
SN = "serialNumber"
TOTAL_ENERGY = "total_kWh"
TYPE = "type"
TYPE_FLOAT = "float"
TYPE_REGISTER = "register"
VOLT = "V"
